entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

max-spawns:
  bat: 0
  blaze: 0
  cave-spider: 0
  chicken: 1
  cow: 1
  creeper: 0
  donkey: 0
  enderman: 0
  ghast: 0
  horse: 0
  iron-golem: 0
  mooshroom: 0
  mule: 0
  ocelot: 0
  pig: 1
  pig-zombie: 0
  rabbit: 0
  silverfish: 0
  sheep: 1
  skeleton: 0
  skeleton-horse: 0
  snow-golem: 0
  spider: 0
  squid: 0
  witch: 0
  wolf: 0
  zombie: 0
  zombie-horse: 0
  zombie-villager: 0